//! # `error-enum-core`
//!
//! A core crate for [`error-enum`](https://crates.io/crates/error-enum) providing
//! traits and implementations for error enums with rich diagnostics support.
//!
//! Please refer to [`error-enum`](https://crates.io/crates/error-enum) and
//! [`its documentation`](https://docs.rs/error-enum/) for more details.
#![warn(unused_crate_dependencies)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]

pub use alloc::{borrow::Cow, boxed::Box, format, string::String};
use core::fmt;
pub use indexer::{Indexer, LineIndexer};
pub use labels::{LabelVec1, SpannedLabel};
pub use mitsein::vec1::{vec1, Vec1};
pub use span::{SimpleSpan, Span};

extern crate alloc;
#[cfg(feature = "std")]
extern crate std;

mod indexer;
mod labels;
mod span;

#[cfg(feature = "annotate-snippets")]
mod annotate_snippets_impl;
#[cfg(feature = "ariadne")]
mod ariadne_impl;
#[cfg(feature = "codespan-reporting")]
mod codespan_reporting_impl;
#[cfg(feature = "miette")]
mod miette_impl;

/// Kind of an additional diagnostic.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AdditionalKind {
    /// Additional note.
    Note,
    /// Additional help.
    Help,
}

/// Iterator over additional diagnostics of an [`ErrorType`].
pub type IterAdditional<T> = Box<
    dyn Iterator<
        Item = (
            <T as ErrorType>::Message,
            LabelVec1<<T as ErrorType>::Span, <T as ErrorType>::Label>,
            AdditionalKind,
        ),
    >,
>;

/// Trait for diagnostic severity / kind types used by [`ErrorType`].
///
/// Implement this for custom kind enums. Each enabled backend feature requires an explicit
/// conversion method; this crate does **not** auto-map unknown kinds.
pub trait DiagnosticKind: Copy + Clone + Default {
    /// Error-code prefix, e.g. `"E"` / `"W"` / `"B"`.
    fn code_prefix(&self) -> &str;

    /// Convert to annotate-snippets annotation type.
    #[cfg(feature = "annotate-snippets")]
    #[cfg_attr(docsrs, doc(cfg(feature = "annotate-snippets")))]
    fn as_annotate_snippets(&self) -> annotate_snippets::snippet::AnnotationType;

    /// Convert to an ariadne report kind.
    #[cfg(feature = "ariadne")]
    #[cfg_attr(docsrs, doc(cfg(feature = "ariadne")))]
    fn as_ariadne(&self) -> ariadne::ReportKind<'static>;

    /// Convert to a codespan-reporting severity.
    #[cfg(feature = "codespan-reporting")]
    #[cfg_attr(docsrs, doc(cfg(feature = "codespan-reporting")))]
    fn as_codespan(&self) -> codespan_reporting::diagnostic::Severity;

    /// Convert to a miette severity.
    #[cfg(feature = "miette")]
    #[cfg_attr(docsrs, doc(cfg(feature = "miette")))]
    fn as_miette(&self) -> miette::Severity;
}

/// Built-in diagnostic kind (`Error` / `Warn`).
#[derive(Clone, Copy, Default, Debug, PartialEq, Eq)]
pub enum Kind {
    /// Error kind.
    #[default]
    Error,
    /// Warning kind.
    Warn,
}

impl Kind {
    /// Get short representation of the [Kind].
    pub fn short_str(&self) -> &'static str {
        match self {
            Kind::Error => "E",
            Kind::Warn => "W",
        }
    }
}

impl DiagnosticKind for Kind {
    fn code_prefix(&self) -> &str {
        self.short_str()
    }

    #[cfg(feature = "annotate-snippets")]
    fn as_annotate_snippets(&self) -> annotate_snippets::snippet::AnnotationType {
        match self {
            Kind::Error => annotate_snippets::snippet::AnnotationType::Error,
            Kind::Warn => annotate_snippets::snippet::AnnotationType::Warning,
        }
    }

    #[cfg(feature = "ariadne")]
    fn as_ariadne(&self) -> ariadne::ReportKind<'static> {
        match self {
            Kind::Error => ariadne::ReportKind::Error,
            Kind::Warn => ariadne::ReportKind::Warning,
        }
    }

    #[cfg(feature = "codespan-reporting")]
    fn as_codespan(&self) -> codespan_reporting::diagnostic::Severity {
        match self {
            Kind::Error => codespan_reporting::diagnostic::Severity::Error,
            Kind::Warn => codespan_reporting::diagnostic::Severity::Warning,
        }
    }

    #[cfg(feature = "miette")]
    fn as_miette(&self) -> miette::Severity {
        match self {
            Kind::Error => miette::Severity::Error,
            Kind::Warn => miette::Severity::Warning,
        }
    }
}

/// Trait for error types generated by [`error_type!`] macro and [`ErrorType`] derive macro.
///
/// For conversion to other diagnostic types, see [`ErrorTypeExt`].
///
/// [`error_type!`]: https://docs.rs/error-enum-macros/latest/error_enum_macros/macro.error_type.html
/// [`ErrorType`]: https://docs.rs/error-enum-macros/latest/error_enum_macros/derive.ErrorType.html
pub trait ErrorType: core::error::Error {
    /// The span type associated with the error type.
    type Span: Span + Default;
    /// The diagnostic kind type (defaults to [`Kind`] via the derive / `error_type!` macros).
    type Kind: DiagnosticKind;
    /// The message type associated with the error type.
    type Message: fmt::Display;
    /// The label type associated with the error type.
    type Label: fmt::Display + Clone;

    /// Get the kind of the error.
    fn kind(&self) -> Self::Kind;
    /// Get the number of the error.
    ///
    /// Non-nested variants typically return [`Cow::Borrowed`]. Nested wrappers return
    /// [`Cow::Owned`] with the outer number prepended to the inner number.
    fn number(&self) -> Cow<'_, str>;
    /// Get the code of the error.
    ///
    /// Default: [`DiagnosticKind::code_prefix`] concatenated with [`number`](Self::number),
    /// e.g. `"E0"`, `"W1"`.
    fn code(&self) -> String {
        alloc::format!("{}{}", self.kind().code_prefix(), self.number())
    }
    /// Get the primary span of the error.
    ///
    /// Equivalent to the span of [`primary_labels`](Self::primary_labels) at index `0`.
    fn primary_span(&self) -> Option<Self::Span>;
    /// Get the primary message of the error.
    fn primary_message(&self) -> Self::Message;
    /// Get the primary labels of the error.
    ///
    /// Index `0` is the primary span label. Further entries are secondary span labels on the
    /// same diagnostic, in attribute declaration order.
    fn primary_labels(&self) -> LabelVec1<Self::Span, Self::Label>;

    /// Get the primary diagnostic of the error.
    fn primary(&self) -> (Self::Message, LabelVec1<Self::Span, Self::Label>) {
        (self.primary_message(), self.primary_labels())
    }

    /// Get additional messages, labels, and kinds of the error.
    ///
    /// Each item is one note or help unit. [`LabelVec1`] index `0` is that unit's anchor label.
    /// Backend renderers group labels with the same source text into one slice or file.
    fn additional(&self) -> IterAdditional<Self>;
}

impl<T: ErrorType + ?Sized> ErrorType for &T {
    type Span = T::Span;
    type Kind = T::Kind;
    type Message = T::Message;
    type Label = T::Label;

    #[inline]
    fn kind(&self) -> Self::Kind {
        (*self).kind()
    }
    #[inline]
    fn number(&self) -> Cow<'_, str> {
        (*self).number()
    }
    #[inline]
    fn code(&self) -> String {
        (*self).code()
    }
    #[inline]
    fn primary_span(&self) -> Option<Self::Span> {
        (*self).primary_span()
    }
    #[inline]
    fn primary_message(&self) -> Self::Message {
        (*self).primary_message()
    }
    #[inline]
    fn primary_labels(&self) -> LabelVec1<Self::Span, Self::Label> {
        (*self).primary_labels()
    }

    #[inline]
    fn primary(&self) -> (Self::Message, LabelVec1<Self::Span, Self::Label>) {
        (*self).primary()
    }

    #[inline]
    fn additional(&self) -> IterAdditional<Self> {
        (*self).additional()
    }
}

/// Conversion to other diagnostic types.
///
/// # Targets
///
/// - [annotate-snippets]
/// - [ariadne]
/// - [codespan-reporting]
/// - [miette]
///
/// ## Label rendering
///
/// [`ErrorType::primary_labels`] and each additional [`LabelVec1`] preserve attribute
/// declaration order. When converting to other diagnostic formats, labels that share the same
/// source text (see [`Span::share_source_text`]) are merged into one slice or file with multiple
/// annotations. Source groups appear in the order of each group's first label.
///
/// ## Backend notes
///
/// [annotate-snippets] fully supports multi-source labels. [codespan-reporting] registers one
/// file per distinct source. [ariadne] deduplicates sources in its cache. [miette] collects all
/// labeled spans in declaration order.
///
/// ### Note vs help
///
/// | Backend              | Note                                             | Help                                            |
/// | -------------------- | ------------------------------------------------ | ----------------------------------------------- |
/// | [annotate-snippets]  | `AnnotationType::Note` on footer and span labels | `AnnotationType::Help`                          |
/// | [ariadne]            | `with_note`                                      | `with_help`                                     |
/// | [codespan-reporting] | `Diagnostic::notes` (`=` bullet)                 | same as note (no separate help channel)         |
/// | [miette]             | spanless notes are not rendered (no note API)    | `Diagnostic::help` (handler adds its own label) |
///
/// User-provided messages are never prefixed with `note:` or `help:` by this crate.
///
/// ### Custom [`DiagnosticKind`]
///
/// Override the kind type with `#[diag(kind_type = "...")]` and implement [`DiagnosticKind`].
/// Each enabled backend feature requires an explicit `as_*` conversion; this crate does not
/// auto-map custom kinds to built-in severities.
///
/// [annotate-snippets]: https://docs.rs/annotate-snippets/0.9.1/annotate_snippets/
/// [ariadne]: https://docs.rs/ariadne/0.6.0/ariadne/
/// [codespan-reporting]: https://docs.rs/codespan-reporting/0.13.1/codespan_reporting/
/// [miette]: https://docs.rs/miette/7.6.0/miette/
pub trait ErrorTypeExt: ErrorType {
    /// Format the error as an [annotate snippet].
    ///
    /// [annotate snippet]: https://docs.rs/annotate-snippets/0.9.1/annotate_snippets/snippet/struct.Snippet.html
    #[cfg(feature = "annotate-snippets")]
    #[cfg_attr(docsrs, doc(cfg(feature = "annotate-snippets")))]
    fn fmt_as_annotate_snippets(&self) -> String {
        annotate_snippets_impl::fmt_as_annotate_snippets(
            self,
            annotate_snippets::display_list::FormatOptions::default(),
        )
    }
    /// Format the error as an [annotate snippet] with [format options].
    ///
    /// [annotate snippet]: https://docs.rs/annotate-snippets/0.9.1/annotate_snippets/snippet/struct.Snippet.html
    /// [format options]: https://docs.rs/annotate-snippets/0.9.1/annotate_snippets/display_list/struct.FormatOptions.html
    #[cfg(feature = "annotate-snippets")]
    #[cfg_attr(docsrs, doc(cfg(feature = "annotate-snippets")))]
    fn fmt_as_annotate_snippets_with_opts(
        &self,
        opts: annotate_snippets::display_list::FormatOptions,
    ) -> String {
        annotate_snippets_impl::fmt_as_annotate_snippets(self, opts)
    }

    /// Format the error as an [Ariadne report].
    ///
    /// [Ariadne report]: https://docs.rs/ariadne/0.6.0/ariadne/struct.Report.html
    #[cfg(feature = "ariadne")]
    #[cfg_attr(docsrs, doc(cfg(feature = "ariadne")))]
    fn fmt_as_ariadne_report(&self) -> Result<String, std::io::Error> {
        ariadne_impl::fmt_as_ariadne_report(
            self,
            ariadne::Config::new().with_index_type(ariadne::IndexType::Byte),
        )
    }
    /// Format the error as an [Ariadne report] with [Ariadne config].
    ///
    /// [Ariadne report]: https://docs.rs/ariadne/0.6.0/ariadne/struct.Report.html
    /// [Ariadne config]: https://docs.rs/ariadne/0.6.0/ariadne/struct.Config.html
    #[cfg(feature = "ariadne")]
    #[cfg_attr(docsrs, doc(cfg(feature = "ariadne")))]
    fn fmt_as_ariadne_report_with(
        &self,
        config: ariadne::Config,
    ) -> Result<String, std::io::Error> {
        ariadne_impl::fmt_as_ariadne_report(self, config)
    }

    /// Format the error as an [Codespan diagnostic].
    ///
    /// [Codespan diagnostic]: https://docs.rs/codespan-reporting/0.13.1/codespan_reporting/diagnostic/struct.Diagnostic.html
    /// [Codespan config]: https://docs.rs/codespan-reporting/0.13.1/codespan_reporting/term/config/struct.Config.html
    #[cfg(feature = "codespan-reporting")]
    #[cfg_attr(docsrs, doc(cfg(feature = "codespan-reporting")))]
    fn as_codespan_diagnostic(
        &self,
    ) -> (
        codespan_reporting::diagnostic::Diagnostic<usize>,
        codespan_reporting_impl::Files<Self>,
    ) {
        codespan_reporting_impl::to_codespan_diagnostic(self)
    }
    /// Format the error as an [Codespan diagnostic] with [Codespan config].
    ///
    /// [Codespan diagnostic]: https://docs.rs/codespan-reporting/0.13.1/codespan_reporting/diagnostic/struct.Diagnostic.html
    /// [Codespan config]: https://docs.rs/codespan-reporting/0.13.1/codespan_reporting/term/config/struct.Config.html
    #[cfg(feature = "codespan-reporting")]
    #[cfg_attr(docsrs, doc(cfg(feature = "codespan-reporting")))]
    fn fmt_as_codespan_diagnostic_with(
        &self,
        config: codespan_reporting::term::Config,
        styles: Option<&codespan_reporting::term::Styles>,
    ) -> Result<String, codespan_reporting::files::Error> {
        codespan_reporting_impl::fmt_as_codespan_diagnostic(self, config, styles)
    }

    /// Convert the error to a [Miette diagnostic].
    ///
    /// [Miette diagnostic]: https://docs.rs/miette/7.6.0/miette/trait.Diagnostic.html
    #[cfg(feature = "miette")]
    #[cfg_attr(docsrs, doc(cfg(feature = "miette")))]
    fn as_miette_diagnostic(&self) -> impl miette::Diagnostic + '_
    where
        Self::Span: Send + Sync,
    {
        miette_impl::Wrapper::new(self)
    }
    /// Format the error as a [Miette diagnostic] with a [Miette handler].
    ///
    /// [Miette diagnostic]: https://docs.rs/miette/7.6.0/miette/trait.Diagnostic.html
    /// [Miette Handler]: https://docs.rs/miette/7.6.0/miette/trait.ReportHandler.html
    #[cfg(feature = "miette")]
    #[cfg_attr(docsrs, doc(cfg(feature = "miette")))]
    fn fmt_as_miette_diagnostic_with(&self, handler: &impl miette::ReportHandler) -> String
    where
        Self: 'static + Sized,
        Self::Span: Send + Sync,
    {
        miette_impl::Wrapper::new(self).fmt_with(handler)
    }
}

impl<T: ErrorType + ?Sized> ErrorTypeExt for T {}
